const canvas = document.querySelector('#gameCanvas');
const ctx = canvas.getContext('2d');
const ui = { hp: document.querySelector('#hpValue'), energy: document.querySelector('#energyValue'), score: document.querySelector('#scoreValue'), wave: document.querySelector('#waveLabel'), progress: document.querySelector('#waveProgress'), towers: document.querySelector('#towerCount'), fps: document.querySelector('#fpsValue') };
const state = { hp:100, energy:120, score:0, wave:1, waveTime:0, spawnTime:0, paused:false, gameOver:false, towers:[], enemies:[], shots:[], particles:[], selected:'pulse' };
const colors = { pulse:'#66e0cf', rail:'#ff936b', enemy:'#ff936b' };
let lastTime = performance.now(); let fpsTimer = 0; let frames = 0;

function resize() { const ratio = Math.min(window.devicePixelRatio || 1, 2); const box = canvas.getBoundingClientRect(); canvas.width = box.width * ratio; canvas.height = box.height * ratio; ctx.setTransform(ratio, 0, 0, ratio, 0, 0); }
function size() { return { w:canvas.clientWidth, h:canvas.clientHeight }; }
function reset() { Object.assign(state, { hp:100, energy:120, score:0, wave:1, waveTime:0, spawnTime:0, paused:false, gameOver:false, towers:[], enemies:[], shots:[], particles:[] }); document.querySelector('#resultDialog').classList.add('hidden'); document.querySelector('#pauseOverlay').classList.add('hidden'); updateUI(); }
function updateUI() { ui.hp.textContent = Math.max(0, Math.ceil(state.hp)); ui.energy.textContent = Math.floor(state.energy); ui.score.textContent = String(state.score).padStart(4,'0'); ui.wave.textContent = `WAVE ${String(state.wave).padStart(2,'0')}`; ui.towers.textContent = `${state.towers.length}/6`; ui.progress.style.width = `${Math.min(100, state.waveTime / 26 * 100)}%`; }
function spawnEnemy() { const { w, h } = size(); const lane = Math.random(); const y = h * (.22 + lane * .58); state.enemies.push({ x:w+28, y, r:10+Math.random()*5, speed:26+state.wave*3+Math.random()*16, hp:1+Math.floor(state.wave/3), maxHp:1+Math.floor(state.wave/3), phase:Math.random()*7 }); }
function addTower(x,y) { if(state.towers.length >= 6) return; const cost = state.selected === 'pulse' ? 30 : 55; if(state.energy < cost) return; state.energy -= cost; state.towers.push({ x,y, type:state.selected, cooldown:0, level:1 }); updateUI(); }
function fire(tower, enemy) { const damage = tower.type === 'rail' ? 2 : 1; state.shots.push({ x:tower.x, y:tower.y, target:enemy, damage, color:colors[tower.type], life:.35 }); tower.cooldown = tower.type === 'rail' ? 1.5 : .65; }
function update(dt) { if(state.paused || state.gameOver) return; state.waveTime += dt; state.spawnTime -= dt; state.energy = Math.min(160, state.energy + dt*3.2); if(state.spawnTime <= 0) { spawnEnemy(); state.spawnTime = Math.max(.38, 1.3 - state.wave*.06); } if(state.waveTime > 26) { state.wave += 1; state.waveTime = 0; state.energy = Math.min(160, state.energy + 25); }
  state.enemies.forEach(enemy => { enemy.x -= enemy.speed*dt; enemy.y += Math.sin(performance.now()/700 + enemy.phase)*dt*10; if(enemy.x < -30) { enemy.dead = true; state.hp -= 8; } });
  state.towers.forEach(tower => { tower.cooldown -= dt; if(tower.cooldown <= 0) { const target = state.enemies.find(enemy => !enemy.dead && Math.hypot(enemy.x-tower.x,enemy.y-tower.y) < 190); if(target) fire(tower,target); } });
  state.shots.forEach(shot => { shot.life -= dt; if(shot.target.dead) return; shot.x += (shot.target.x-shot.x)*Math.min(1,dt*14); shot.y += (shot.target.y-shot.y)*Math.min(1,dt*14); if(Math.hypot(shot.target.x-shot.x,shot.target.y-shot.y)<12) { shot.target.hp -= shot.damage; shot.target.dead = shot.target.hp <= 0; if(shot.target.dead) { state.score += shot.target.maxHp*10; burst(shot.target.x,shot.target.y,shot.color); } } });
  state.enemies = state.enemies.filter(enemy => !enemy.dead); state.shots = state.shots.filter(shot => shot.life > 0 && !shot.target.dead); state.particles.forEach(p => { p.life -= dt; p.x += p.vx*dt; p.y += p.vy*dt; }); state.particles = state.particles.filter(p => p.life > 0); if(state.hp <= 0) finish(false); updateUI(); }
function burst(x,y,color) { for(let i=0;i<8;i++) state.particles.push({x,y,vx:(Math.random()-.5)*80,vy:(Math.random()-.5)*80,life:.45,color}); }
function draw() { const {w,h}=size(); ctx.clearRect(0,0,w,h); ctx.fillStyle='#09191b'; ctx.fillRect(0,0,w,h); ctx.strokeStyle='rgba(120,210,200,.08)'; ctx.lineWidth=1; for(let x=0;x<w;x+=38){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();} for(let y=0;y<h;y+=38){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();} ctx.strokeStyle='rgba(102,224,207,.16)'; ctx.setLineDash([5,9]); ctx.beginPath();ctx.moveTo(0,h*.5);ctx.lineTo(w,h*.5);ctx.stroke();ctx.setLineDash([]);
  state.towers.forEach(t=>{ctx.beginPath();ctx.arc(t.x,t.y,25,0,Math.PI*2);ctx.strokeStyle='rgba(102,224,207,.16)';ctx.stroke();ctx.fillStyle=colors[t.type];ctx.fillRect(t.x-8,t.y-8,16,16);ctx.strokeStyle='#d6fffa';ctx.strokeRect(t.x-5,t.y-5,10,10);});
  state.enemies.forEach(e=>{ctx.save();ctx.translate(e.x,e.y);ctx.rotate(Math.PI/4);ctx.fillStyle=colors.enemy;ctx.fillRect(-e.r/1.4,-e.r/1.4,e.r*1.4,e.r*1.4);ctx.restore();ctx.fillStyle='rgba(255,255,255,.18)';ctx.fillRect(e.x-12,e.y-e.r-9,24,2);ctx.fillStyle=colors.enemy;ctx.fillRect(e.x-12,e.y-e.r-9,24*(e.hp/e.maxHp),2);});
  state.shots.forEach(s=>{ctx.beginPath();ctx.arc(s.x,s.y,3,0,Math.PI*2);ctx.fillStyle=s.color;ctx.shadowBlur=14;ctx.shadowColor=s.color;ctx.fill();ctx.shadowBlur=0;}); state.particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,3,3);ctx.globalAlpha=1;}); }
function finish(won) { state.gameOver = true; document.querySelector('#resultTitle').textContent = won ? '航道已守住' : '核心失守'; document.querySelector('#resultText').textContent = `完成 ${state.wave} 个波次，最终得分 ${state.score}。`; document.querySelector('#resultDialog').classList.remove('hidden'); }
function loop(now) { const dt=Math.min(.05,(now-lastTime)/1000); lastTime=now; update(dt); draw(); frames++; fpsTimer+=dt; if(fpsTimer>1){ui.fps.textContent=frames;frames=0;fpsTimer=0;} requestAnimationFrame(loop); }
canvas.addEventListener('pointerdown', e=>{const r=canvas.getBoundingClientRect();addTower(e.clientX-r.left,e.clientY-r.top);});
document.querySelectorAll('.tower-card').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.tower-card').forEach(item=>item.classList.remove('selected'));button.classList.add('selected');state.selected=button.dataset.type;}));
document.querySelector('#pauseButton').addEventListener('click',()=>{state.paused=!state.paused;document.querySelector('#pauseOverlay').classList.toggle('hidden',!state.paused);}); document.querySelector('#resumeButton').addEventListener('click',()=>{state.paused=false;document.querySelector('#pauseOverlay').classList.add('hidden');}); document.querySelector('#restartButton').addEventListener('click',reset); document.querySelector('#resultButton').addEventListener('click',reset); window.addEventListener('resize',resize); resize(); reset(); requestAnimationFrame(loop);